name: .NET Core 2.2
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.nuspec'
      - 'Lame.Test.Framework/**'
      - '.git*'
      - '!.git*/**.yml'

jobs:
  ci:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup .NET Core 2.2.108
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build LameDLLWrap (Debug|x86)
      run: dotnet build LameDLLWrap -c:Debug -p:Platform=x86
    - name: Build LameDLLWrap (Debug|x64)
      run: dotnet build LameDLLWrap -c:Debug -p:Platform=x64
    - name: Build NAudio.Lame
      run: dotnet build NAudio.Lame -c:Debug -p:Platform=AnyCPU
    - name: Build Lame.Test.Core
      run: dotnet build Lame.Test.Core -c:Debug -p:Platform=AnyCPU
    - name: Run tests
      run: dotnet test
