name: .NET Core 2.2
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.nuspec'
      - 'Lame.Test.Framework/**'
      - '.git*'
      - '!.git*/**.yml'

jobs:
  ci:
    runs-on: windows-latest
    strategy:
      matrix:
        dnversion: ['3.1.x', '2.1.x']

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core ${{ matrix.dnversion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dnversion }}

    - uses: microsoft/setup-msbuild@v1.0.1
      with:
        vs-version: '16.x'
    - uses: darenm/Setup-VSTest@v1
    - uses: NuGet/setup-nuget@v1.0.2
      
    - name: Restore packages
      run: nuget restore NAudio.Lame.sln

    - name: Build LameDLLWrap (Debug|x86)
      run: dotnet build LameDLLWrap -c:Debug -p:Platform=x86
    - name: Build LameDLLWrap (Debug|x64)
      run: dotnet build LameDLLWrap -c:Debug -p:Platform=x64
    - name: Build LameDLLWrap (Debug|AnyCPU)
      run: dotnet build LameDLLWrap -c:Debug -p:Platform=AnyCPU
    - name: Build NAudio.Lame
      run: dotnet build NAudio.Lame -c:Debug -p:Platform=AnyCPU
    - name: Build Lame.Test.Core
      run: dotnet build Lame.Test.Core -c:Debug -p:Platform=AnyCPU
    - name: Run .NET Core tests
      run: dotnet test Lame.Test.Core
    - name: Build Lame.Test.Framework
      run: dotnet build Lame.Test.Framework -c:Debug -p:Platform=AnyCPU
    - name: Run Framework tests
      run: vstest.console.exe Lame.Test.Framework\bin\Debug\Lame.Test.Framework.dll
